# Part 2. Vector and Matrix

In this lab, we will learn how to use Python to operate vectors and matrices. 

## 1. Example

### 1.1 Load data with pandas

In [3]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


### 1.2 Operation for vector

In [4]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [5]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X

In [16]:
# this is your code to get two vectors
#m3=X[:,(0,-2)]
m3=X[:,0]
m4=X[:,-2]
print(m3[0:15])
print(m4[0:15])


[18.0 15.0 18.0 16.0 17.0 15.0 14.0 14.0 14.0 15.0 0.0 0.0 0.0 0.0 0.0]
[12.0 11.5 11.0 12.0 10.5 10.0 9.0 8.5 10.0 8.5 17.5 11.5 11.0 10.5 11.0]


### 2.2 Perform following operations on these two vectors and print the result

In [17]:

# 1. addition and subtraction
additionSubtraction=m3+m4
#print(additionSubtraction)
# 2. element-wise multiplication
multiplication=m3*m4
#print(multiplication)
# 3. inner product
dotProduct=np.inner(m3,m4)
print(dotProduct)
# 4. three norms
l1=np.linalg.norm(m3,1)
l2=np.linalg.norm(m3,2)
l3=np.linalg.norm(m3,3)
print(l1,l2,l3)
# 5. compute the distance between these two vectors
dist = np.linalg.norm(m3 - m4)
print(dist)

149295.04000000004
9358.800000000003 494.28813459357895 191.0366358641296
216.10913909411607


### 2.3 Get the first three columns and the last three columns from X

In [22]:
# this is your code to get two matrices: A, B
A=X[:,(0,1,2)]
B=X[:,(-1,-2,-3)]

print(A, B)

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]
 ...
 [32.0 4 135.0]
 [28.0 4 120.0]
 [31.0 4 119.0]] [[70 12.0 3504]
 [70 11.5 3693]
 [70 11.0 3436]
 ...
 [82 11.6 2295]
 [82 18.6 2625]
 [82 19.4 2720]]


### 2.4 Perform following operations on these two matrices and print the result

In [25]:
# 1. addition and subtraction 
add=A+B
#print(add)
# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
c=np.transpose(B)
print(c.shape)
# 3. compute the product between A and C, and print the result and its shape
AC=np.dot(A,c)
print(AC.shape)
print(AC)
# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D=np.transpose(A)
print(D.shape)
# 5. compute the product between D and B, and print the result and its shape
DB=np.dot(D,B)
print(DB.shape)
print(DB)

(3, 406)
(406, 406)
[[1077084.0 1135103.0 1056200.0 ... 706133.8 807499.8 836671.2]
 [1227546.0 1293692.0 1203738.0 ... 804572.8 920128.8 953385.2]
 [1115628.0 1175726.0 1093996.0 ... 731378.8 836374.8 866591.2]
 ...
 [475328.0 500841.0 466144.0 ... 312495.4 357073.4 369901.6]
 [422488.0 445166.0 414324.0 ... 277742.4 317370.4 328773.6]
 [419194.0 441683.0 411098.0 ... 275693.4 314991.4 326299.6]]
